spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rakuraku-curry}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:KYj5nbht}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: ${LOG_FILE_PATH:logs/curry.log}

# 商品一覧の画像のURLにsessionidが勝手に混入し画像がリンク切れになる不具合対応の設定
server:
  servlet:
    session:
      tracking-modes: cookie
# メール送信設定
custom:
  mail:
    from: support@rakuraku-curry.com
    subject: ご注文ありがとうございます【ラクラクカレー】
    template: "src/main/resources/mail/order-complete.txt"
